// =============================================
//  NOIR MUSIC PLAYER — DATA
//  Agrega tus propias canciones aquí.
//  Coloca los archivos .mp3 en /assets/audio/
//  y las imágenes en /assets/covers/
// =============================================

const SONGS = [
  {
    id: 1,
    title: "mujer amante",
    artist: "rata blanca",
    duration: "6:01",
    durationSec: 361,
    // src: "assets/audio/blinding-lights.mp3",  // Descomenta y agrega tu archivo
    src: "js/Rata Blanca - Mujer Amante (Audio).mp3",
    cover: "js/mujer amante.png",   // "assets/covers/blinding-lights.jpg"
    emoji: "🌆",
    liked: false,
  },
  {
    id: 2,
    title: "Cementery Gates",
    artist: "The Smiths",
    duration: "2:37",
    durationSec: 157,
    src: "js/The Smiths - Cemetry Gates (Official Audio).mp3",
    cover: "js/cementery.png",
    emoji: "🔥",
    liked: false,
  },
  {
    id: 3,
    title: "walk",
    artist: "pantera",
    duration: "5:19",
    durationSec: 319,
    src: "js/Pantera - Walk.mp3",
    cover: "js/walk.png",
    emoji: "👑",
    liked: true,
  },
  {
    id: 4,
    title: "london dungeon",
    artist: "misfits",
    duration: "2:24",
    durationSec: 144,
    src: "js/London Dungeon.mp3",
    cover: "js/london.jpeg",
    emoji: "💜",
    liked: false,
  },
  {
    id: 5,
    title: "soñe",
    artist: "Zoe",
    duration: "3:17",
    durationSec: 197,
    src: "js/Soñé.mp3",
    cover: "js/soñe.png",
    emoji: "⚡",
    liked: false,
  },
  {
    id: 6,
    title: "kumbala",
    artist: "maldita vecindad ",
    duration: "4:27",
    durationSec: 267,
    src: "js/Kumbala.mp3",
    cover: "js/kumbala.png",
    emoji: "🎺",
    liked: false,
  },
  {
    id: 7,
    title: "Querer querernos(vercion acustica)",
    artist: "Cancerbero",
    duration: "3:58",
    durationSec: 238,
    src: "js/Canserbero - Querer Querernos (Versión Acústica).mp3",
    cover: "js/querer.png",
    emoji: "⭐",
    liked: true,
  },
  {
    id: 8,
    title: "La celula que explota",
    artist: "Caifanes",
    duration: "3:49",
    durationSec: 229,
    src: "js/Caifanes - La Célula Que Explota (Letra  Lyrics).mp3",
    cover: "js/celula.png",
    emoji: "🌳",
    liked: false,
  },
  {
    id: 9,
    title: "Triste cancion",
    artist: "El tri",
    duration: "5:43",
    durationSec: 343,
    src: "js/Triste canción.mp3",
    cover: "js/triste.png",
    emoji: "🏀",
    liked: false,
  },
  {
    id: 10,
    title: "Oye mi amor",
    artist: "Mana",
    duration: "2:57",
    durationSec: 177,
    src: "js/Oye Mi Amor.mp3",
    cover: "js/oye.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 11,
    title: "brillas",
    artist: "Leon Larregui",
    duration: "4:10",
    durationSec: 250,
    src: "js/León Larregui - Brillas (Video Oficial).mp3",
    cover: "js/brillas.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 12,
    title: "2013",
    artist: "zoe",
    duration: "4:30",
    durationSec: 270,
    src: "js/Zoé - Dos Mil Trece (Audio).mp3",
    cover: "js/2013.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 13,
    title: "10 A.M",
    artist: "zoe",
    duration: "3:47",
    durationSec: 227,
    src: "js/Zoé - 10 A.M..mp3",
    cover: "js/2013.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 14,
    title: "Arrullo de estrellas",
    artist: "zoe",
    duration: "4:13",
    durationSec: 253,
    src: "js/Zoé - Arrullo De Estrellas (Lyric Video).mp3",
    cover: "js/2013.png",
    emoji: "🌙",
    liked: false,
  },
  // ===== ZOÉ =====
{
  id: 15,
  title: "Nada",
  artist: "Zoé",
  duration: "4:02",
  durationSec: 242,
  src: "js/Zoe - Nada ft. Enrique Bunbury.mp3",
  cover: "js/nada,ong.jpeg",
  emoji: "🌙",
  liked: false,
},
{
  id: 16,
  title: "Labios Rotos",
  artist: "Zoé",
  duration: "3:48",
  durationSec: 228,
  src: "js/Zoé - Labios Rotos (MTV Unplugged).mp3",
  cover: "js/labios.png",
  emoji: "💜",
  liked: false,
},
{
  id: 17,
  title: "No me destruyas",
  artist: "Zoé",
  duration: "3:46",
  durationSec: 226,
  src: "js/Zoé - No Me Destruyas (MTV Unplugged).mp3",
  cover: "js/no.png",
  emoji: "🖤",
  liked: false,
},
{
  id: 18,
  title: "Luna",
  artist: "Zoé",
  duration: "5:11",
  durationSec: 311,
  src: "js/Zoé - Luna (MTV Unplugged).mp3",
  cover: "js/labios.png",
  emoji: "🌕",
  liked: false,
},

// ===== THE SMITHS =====
{
  id: 19,
  title: "There Is a Light That Never Goes Out",
  artist: "The Smiths",
  duration: "4:01",
  durationSec: 241,
  src: "js/The Smiths - There Is A Light That Never Goes Out (Official Audio).mp3",
  cover: "js/there.png",
  emoji: "🕯️",
  liked: false,
},
{
  id: 20,
  title: "How Soon Is Now?",
  artist: "The Smiths",
  duration: "6:41",
  durationSec: 401,
  src: "js/The Smiths - How Soon Is Now_ (Official Music Video).mp3",
  cover: "js/soon.png",
  emoji: "🎸",
  liked: false,
},
{
  id: 21,
  title: "This Charming Man",
  artist: "The Smiths",
  duration: "2:42",
  durationSec: 162,
  src: "js/The Smiths - This Charming Man (Official Music Video).mp3",
  cover: "js/man.png",
  emoji: "🌹",
  liked: false,
},


// ===== CAIFANES =====
{
  id: 23,
  title: "La Negra Tomasa",
  artist: "Caifanes",
  duration: "7:54",
  durationSec: 474,
  src: "js/Caifanes - La Negra Tomasa (Bilongo (Versión Tropical)[Cover Audio]).mp3",
  cover: "js/caifanes mo.png",
  emoji: "🌺",
  liked: false,
},
{
  id: 24,
  title: "Afuera",
  artist: "Caifanes",
  duration: "4:59",
  durationSec: 299,
  src: "js/Caifanes - Afuera (Cover Audio).mp3",
  cover: "js/afuera.png",
  emoji: "🌑",
  liked: false,
},
{
  id: 25,
  title: "Miércoles de Ceniza",
  artist: "Caifanes",
  duration: "4:54",
  durationSec: 294,
  src: "js/Caifanes - Miércoles De Ceni ((Cover Audio)(Video)).mp3",
  cover: "js/m.png",
  emoji: "🕊️",
  liked: false,
},
{
  id: 26,
  title: "No Dejes Que",
  artist: "Caifanes",
  duration: "4:41",
  durationSec: 281,
  src: "js/Caifanes - No Dejes Qué... ((Cover Audio)(Video)).mp3",
  cover: "js/m.png",
  emoji: "💔",
  liked: false,
},

// ===== ZOÉ =====
{
  id: 27,
  title: "Vía Láctea",
  artist: "Zoé",
  duration: "4:50",
  durationSec: 290,
  src: "js/Zoé - Vía Láctea (MTV Unplugged).mp3",
  cover: "js/no.png",
  emoji: "🌌",
  liked: false,
},

// ===== THE SMITHS =====
{
  id: 28,
  title: "The Boy with the Thorn in His Side",
  artist: "The Smiths",
  duration: "3:17",
  durationSec: 197,
  src: "js/The Smiths - The Boy With The Thorn In His Side (Official Music Video).mp3",
  cover: "js/boy.png",
  emoji: "🌿",
  liked: false,
},
{
  id: 29,
  title: "Girlfriend in a Coma",
  artist: "The Smiths",
  duration: "2:02",
  durationSec: 122,
  src: "js/The Smiths - Girlfriend In A Coma (Official Music Video).mp3",
  cover: "js/girl.png",
  emoji: "🖤",
  liked: false,
},
{
  id: 30,
  title: "Bigmouth Strikes Again",
  artist: "The Smiths",
  duration: "3:12",
  durationSec: 192,
  src: "js/The Smiths - Bigmouth Strikes Again (Official Audio).mp3",
  cover: "js/there.png",
  emoji: "🎙️",
  liked: false,
},

// ===== CAIFANES =====
{
  id: 31,
  title: "Aquí No Es Así",
  artist: "Caifanes",
  duration: "4:56",
  durationSec: 296,
  src: "js/Caifanes - Aquí No Es Así (Cover Audio).mp3",
  cover: "js/afuera.png",
  emoji: "🕊️",
  liked: false,
},
{
  id: 32,
  title: "Antes de Que Nos Olviden",
  artist: "Caifanes",
  duration: "4:48",
  durationSec: 288,
  src: "js/Caifanes - Antes de Que Nos Olviden (Cover Audio).mp3",
  cover: "js/antes.png",
  emoji: "💔",
  liked: false,
},

// ===== RATA BLANCA =====
{
  id: 33,
  title: "El Camino del Sol",
  artist: "Rata Blanca",
  duration: "9:25",
  durationSec: 565,
  src: "js/Rata Blanca - El Camino Del Sol (Audio).mp3",
  cover: "js/mujer amante.png",
  emoji: "⚔️",
  liked: false,
},
{
  id: 34,
  title: "La Leyenda del Hada y el Mago",
  artist: "Rata Blanca",
  duration: "5:21",
  durationSec: 321,
  src: "js/Rata Blanca - La Leyenda Del Hada Y El Mago (Audio).mp3",
  cover: "js/mujer amante.png",
  emoji: "🧙",
  liked: false,
},


];

// Playlists guardadas en localStorage
function loadPlaylists() {
  try {
    return JSON.parse(localStorage.getItem("noir_playlists")) || [];
  } catch { return []; }
}

function savePlaylists(playlists) {
  localStorage.setItem("noir_playlists", JSON.stringify(playlists));
}

let PLAYLISTS = loadPlaylists();
