const SONGS = [
  {
    id: 1,
    title: "mujer amante",
    artist: "rata blanca",
    duration: "6:01",
    durationSec: 361,
    src: "Rata Blanca - Mujer Amante (Audio).mp3",
    cover: "mujer amante.png",
    emoji: "🌆",
    liked: false,
  },
  {
    id: 2,
    title: "Cementery Gates",
    artist: "The Smiths",
    duration: "2:37",
    durationSec: 157,
    src: "The Smiths - Cemetry Gates (Official Audio).mp3",
    cover: "cementery.png",
    emoji: "🔥",
    liked: false,
  },
  {
    id: 3,
    title: "walk",
    artist: "pantera",
    duration: "5:19",
    durationSec: 319,
    src: "Pantera - Walk.mp3",
    cover: "walk.png",
    emoji: "👑",
    liked: true,
  },
  {
    id: 4,
    title: "london dungeon",
    artist: "misfits",
    duration: "2:24",
    durationSec: 144,
    src: "London Dungeon.mp3",
    cover: "london.jpeg",
    emoji: "💜",
    liked: false,
  },
  {
    id: 5,
    title: "soñe",
    artist: "Zoe",
    duration: "3:17",
    durationSec: 197,
    src: "Soñé.mp3",
    cover: "soñe.png",
    emoji: "⚡",
    liked: false,
  },
  {
    id: 6,
    title: "kumbala",
    artist: "maldita vecindad ",
    duration: "4:27",
    durationSec: 267,
    src: "Kumbala.mp3",
    cover: "kumbala.png",
    emoji: "🎺",
    liked: false,
  },
  {
    id: 7,
    title: "Querer querernos(vercion acustica)",
    artist: "Cancerbero",
    duration: "3:58",
    durationSec: 238,
    src: "Canserbero - Querer Querernos (Versión Acústica).mp3",
    cover: "querer.png",
    emoji: "⭐",
    liked: true,
  },
  {
    id: 8,
    title: "La celula que explota",
    artist: "Caifanes",
    duration: "3:49",
    durationSec: 229,
    src: "Caifanes - La Célula Que Explota (Letra  Lyrics).mp3",
    cover: "celula.png",
    emoji: "🌳",
    liked: false,
  },
  {
    id: 9,
    title: "Triste cancion",
    artist: "El tri",
    duration: "5:43",
    durationSec: 343,
    src: "Triste canción.mp3",
    cover: "triste.png",
    emoji: "🏀",
    liked: false,
  },
  {
    id: 10,
    title: "Oye mi amor",
    artist: "Mana",
    duration: "2:57",
    durationSec: 177,
    src: "Oye Mi Amor.mp3",
    cover: "oye.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 11,
    title: "brillas",
    artist: "Leon Larregui",
    duration: "4:10",
    durationSec: 250,
    src: "León Larregui - Brillas (Video Oficial).mp3",
    cover: "brillas.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 12,
    title: "2013",
    artist: "zoe",
    duration: "4:30",
    durationSec: 270,
    src: "Zoé - Dos Mil Trece (Audio).mp3",
    cover: "2013.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 13,
    title: "10 A.M",
    artist: "zoe",
    duration: "3:47",
    durationSec: 227,
    src: "Zoé - 10 A.M..mp3",
    cover: "2013.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 14,
    title: "Arrullo de estrellas",
    artist: "zoe",
    duration: "4:13",
    durationSec: 253,
    src: "Zoé - Arrullo De Estrellas (Lyric Video).mp3",
    cover: "2013.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 15,
    title: "Nada",
    artist: "Zoé",
    duration: "4:02",
    durationSec: 242,
    src: "Zoe - Nada ft. Enrique Bunbury.mp3",
    cover: "nada.png",
    emoji: "🌙",
    liked: false,
  },
  {
    id: 16,
    title: "Labios Rotos",
    artist: "Zoé",
    duration: "3:48",
    durationSec: 228,
    src: "Zoé - Labios Rotos (MTV Unplugged).mp3",
    cover: "labios.png",
    emoji: "💜",
    liked: false,
  },
  {
    id: 17,
    title: "No me destruyas",
    artist: "Zoé",
    duration: "3:46",
    durationSec: 226,
    src: "Zoé - No Me Destruyas (MTV Unplugged).mp3",
    cover: "no.png",
    emoji: "🖤",
